#!/usr/bin/env python3

"""
Cellebrite Environment Troubleshooter
Author: Emanuela Signor
Purpose: Diagnose common issues affecting Cellebrite UFED operation
Environment: Kali Linux / Ubuntu / Debian-based systems
"""

import os
import subprocess
import shutil
from datetime import datetime


def run_command(cmd):
    """Run shell command and return output"""
    try:
        result = subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT)
        return result.decode()
    except subprocess.CalledProcessError as e:
        return e.output.decode()


def check_java():
    print("\n[+] Checking Java installation...")
    output = run_command("java -version")
    if "version" in output:
        print("[OK] Java detected")
        print(output.split("\n")[0])
    else:
        print("[ERROR] Java not found")


def check_usb_devices():
    print("\n[+] Checking USB device connectivity...")
    output = run_command("lsusb")
    if output.strip():
        print("[OK] USB devices detected")
        print(output)
    else:
        print("[ERROR] No USB devices found")


def check_disk_space():
    print("\n[+] Checking disk space...")
    total, used, free = shutil.disk_usage("/")
    
    print(f"Total: {total // (2**30)} GB")
    print(f"Used: {used // (2**30)} GB")
    print(f"Free: {free // (2**30)} GB")

    if free < 5 * (2**30):
        print("[WARNING] Low disk space may affect extractions")


def check_permissions():
    print("\n[+] Checking user permissions...")
    output = run_command("groups")

    if "sudo" in output:
        print("[OK] User has sudo privileges")
    else:
        print("[WARNING] User may lack admin permissions")


def check_running_processes():
    print("\n[+] Checking for Cellebrite processes...")
    output = run_command("ps aux | grep -i cellebrite | grep -v grep")

    if output.strip():
        print("[INFO] Cellebrite processes detected:")
        print(output)
    else:
        print("[INFO] No active Cellebrite processes")


def check_logs():
    print("\n[+] Checking typical log locations...")
    possible_logs = [
        "/var/log/",
        os.path.expanduser("~/"),
    ]

    for path in possible_logs:
        print(f"[INFO] Inspecting: {path}")


def main():
    print("=" * 50)
    print(" Cellebrite Troubleshooting Script")
    print(" Generated by Emanuela Signor")
    print(f" Time: {datetime.now()}")
    print("=" * 50)

    check_java()
    check_usb_devices()
    check_disk_space()
    check_permissions()
    check_running_processes()
    check_logs()

    print("\n[+] Troubleshooting complete")


if __name__ == "__main__":
    main()
